name: Schedule Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # Déclenchement tous les jours à minuit UTC

jobs:
  scheduled_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2