name: Workflow2

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    env : 
        username : ${{ secrets.DOCKER_USERNAME }}
        password : ${{ secrets.DOCKER_USERNAME }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run Python Script
      run: python script.py

    - name: Build Docker Image
      run: docker build -t scipt1 .

    - name: Run Unit Tests
      run: python -m pytest tests/test_script1.py

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: "mohamedfarsi"
        password: "dckr_pat_rltnR1QeQ_f-Iv46_t9VmdvtDvs"

    - name: Push Docker Image 
      run: docker push mohamedfarsi/app1:3.0